//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeDorm
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string OldDormNum { get; set; }
        public string NewDormNum { get; set; }
        public string Why { get; set; }
        public System.DateTime Begindate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<System.DateTime> AgreeDate { get; set; }
        public Nullable<bool> StaffOpinion { get; set; }
        public Nullable<bool> StudentOpinion { get; set; }
    
        public virtual Dorm Dorm { get; set; }
        public virtual Dorm Dorm1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
