//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormHygiene
    {
        public int Id { get; set; }
        public string DormNum { get; set; }
        public Nullable<System.DateTime> InspectionTime { get; set; }
        public string Situation { get; set; }
    
        public virtual Dorm Dorm { get; set; }
    }
}
